common: &COMMON
  env:
    HOME: /tmp # cargo needs it
    RUST_BACKTRACE: full  # Better info for debugging test failures.
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all

task:
  env:
    VERSION: 1.53.0
  matrix:
    - name: FreeBSD 11.4 MSRV
      freebsd_instance:
        image: freebsd-11-4-release-amd64
  << : *COMMON
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: FreeBSD 13.0 nightly
  env:
    VERSION: nightly
  freebsd_instance:
    image: freebsd-13-0-release-amd64
  << : *COMMON
  clippy_script:
    - . $HOME/.cargo/env
    - rustup component add clippy
    - cargo clippy --all-features --all-targets -- -D warnings
  # Test our minimal version spec
  # Disabled until sysctl-rs fixes its own build
  # https://github.com/johalun/sysctl-rs/pull/37
  #minver_test_script:
  #- . $HOME/.cargo/env
  #- cargo update -Zminimal-versions
  #- cargo check --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
